apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: reader
      initContainers:
      - name: aws-cli
        image: amazon/aws-cli
        command: ['aws', 's3', 'cp', 's3://bucket-name/file-name', '-']
      containers:
      - name: nginx  
        image: nginx:latest
        ports:
        - containerPort: 80
